language: java
sudo: false

cache:
  directories:
    - "$HOME/.m2"
install:
  - mvn install -DskipTests=true -DskipITs=true -Dmaven.javadoc.skip=true -B -V --toolchains .m2/travis-ci-toolchains.xml

jobs:
  include:
    # 1.1 Tests
    - stage: test
      jdk: openjdk11
      script: mvn verify --toolchains .m2/travis-ci-toolchains.xml
      env: VERIFY=true

    # 1.2 Coverage
    - stage: test
      jdk: openjdk11
      script: mvn jacoco:prepare-agent verify jacoco:report coveralls:report --toolchains .m2/travis-ci-toolchains.xml
      env: COVERAGE=true

    # 1.3 Javadoc
    - jdk: openjdk11
      env: JAVADOC=true
      script:
        - mvn javadoc:jar --toolchains .m2/travis-ci-toolchains.xml

branches:
  only:
  - master
